# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Modulo4_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#Disenio hecho por Abraham Ortiz Castro y Jesús Alejandro Gomez Bautista
#Fecha 27/04/2023

#Se importa la libreria para trabajar con PyQt5.
from PyQt5 import QtCore, QtGui, QtWidgets

#Se define la clase para la interfaz gráfica
class Ui_InterfazGrafica(object):
    #Se definen todos los objetos de la interfaz grafica
    def setupUi(self, InterfazGrafica):
        #Se inicializa la interfaz gráficas
        InterfazGrafica.setObjectName("InterfazGrafica")
        InterfazGrafica.resize(809, 705)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        InterfazGrafica.setFont(font)
        InterfazGrafica.setAutoFillBackground(True)
        #Se inicializa el central widget
        self.centralwidget = QtWidgets.QWidget(InterfazGrafica)
        self.centralwidget.setObjectName("centralwidget")
        self.title_window = QtWidgets.QTextEdit(self.centralwidget)
        #Se crea la ventana del windows
        self.title_window.setEnabled(True)
        self.title_window.setGeometry(QtCore.QRect(190, 20, 411, 51))
        self.title_window.setAutoFillBackground(True)
        self.title_window.setReadOnly(True)
        self.title_window.setObjectName("title_window")
        #Se crea la figura subt_1
        self.subt_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.subt_1.setEnabled(True)
        self.subt_1.setGeometry(QtCore.QRect(-20, 90, 831, 31))
        self.subt_1.setAutoFillBackground(True)
        self.subt_1.setReadOnly(True)
        self.subt_1.setObjectName("subt_1")
        #Se crea la figura subt_2
        self.subt_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.subt_2.setEnabled(True)
        self.subt_2.setGeometry(QtCore.QRect(-20, 450, 831, 31))
        self.subt_2.setAutoFillBackground(True)
        self.subt_2.setReadOnly(True)
        self.subt_2.setObjectName("subt_2")
        #Se crea el boton para confirmar acción
        self.btt_analizar = QtWidgets.QPushButton(self.centralwidget)
        self.btt_analizar.setGeometry(QtCore.QRect(340, 600, 121, 28))
        self.btt_analizar.setObjectName("btt_analizar")
        #Se crea title_NV
        self.title_NV = QtWidgets.QTextEdit(self.centralwidget)
        self.title_NV.setEnabled(True)
        self.title_NV.setGeometry(QtCore.QRect(140, 500, 171, 31))
        self.title_NV.setAutoFillBackground(True)
        self.title_NV.setReadOnly(True)
        self.title_NV.setObjectName("title_NV")
        # Se crea title_NC
        self.title_NC = QtWidgets.QTextEdit(self.centralwidget)
        self.title_NC.setEnabled(True)
        self.title_NC.setGeometry(QtCore.QRect(480, 500, 171, 31))
        self.title_NC.setAutoFillBackground(True)
        self.title_NC.setReadOnly(True)
        self.title_NC.setObjectName("title_NC")
        # Se crea title_FN
        self.title_FN = QtWidgets.QTextEdit(self.centralwidget)
        self.title_FN.setEnabled(True)
        self.title_FN.setGeometry(QtCore.QRect(320, 130, 171, 31))
        self.title_FN.setAutoFillBackground(True)
        self.title_FN.setReadOnly(True)
        self.title_FN.setObjectName("title_FN")
        # Se crea title_txtwrite
        self.title_txtwrite = QtWidgets.QTextEdit(self.centralwidget)
        self.title_txtwrite.setEnabled(True)
        self.title_txtwrite.setGeometry(QtCore.QRect(320, 210, 171, 31))
        self.title_txtwrite.setAutoFillBackground(True)
        self.title_txtwrite.setReadOnly(True)
        self.title_txtwrite.setObjectName("title_txtwrite")
        # Se crea title_LF
        self.title_LF = QtWidgets.QTextEdit(self.centralwidget)
        self.title_LF.setEnabled(True)
        self.title_LF.setGeometry(QtCore.QRect(190, 380, 231, 31))
        self.title_LF.setAutoFillBackground(True)
        self.title_LF.setReadOnly(True)
        self.title_LF.setObjectName("title_LF")
        # Se crea recuadro establecer num lineas
        self.N_lineas = QtWidgets.QTextEdit(self.centralwidget)
        self.N_lineas.setGeometry(QtCore.QRect(430, 380, 211, 31))
        self.N_lineas.setObjectName("N_lineas")
        #Se crea recuadro nombre del archuvo
        self.file_name = QtWidgets.QLineEdit(self.centralwidget)
        self.file_name.setGeometry(QtCore.QRect(270, 170, 281, 31))
        self.file_name.setObjectName("file_name")
        # Se crea recuadro para ingresar texto
        self.txt = QtWidgets.QTextEdit(self.centralwidget)
        self.txt.setGeometry(QtCore.QRect(100, 250, 601, 111))
        self.txt.setObjectName("txt")
        # Se crea NC_output
        self.NC_output = QtWidgets.QLineEdit(self.centralwidget)
        self.NC_output.setGeometry(QtCore.QRect(460, 540, 211, 41))
        self.NC_output.setObjectName("NC_output")
        # Se crear NV_output
        self.NV_output = QtWidgets.QLineEdit(self.centralwidget)
        self.NV_output.setGeometry(QtCore.QRect(120, 540, 211, 41))
        self.NV_output.setObjectName("NV_output")
        InterfazGrafica.setCentralWidget(self.centralwidget)
        # Se crea statusbar
        self.statusbar = QtWidgets.QStatusBar(InterfazGrafica)
        self.statusbar.setObjectName("statusbar")
        InterfazGrafica.setStatusBar(self.statusbar)
        # Se crea toolbar
        self.toolBar = QtWidgets.QToolBar(InterfazGrafica)
        self.toolBar.setObjectName("toolBar")
        InterfazGrafica.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        #Se define acción esc
        self.actionEsc = QtWidgets.QAction(InterfazGrafica)
        self.actionEsc.setObjectName("actionEsc")
        #Se manda la interfaz
        self.retranslateUi(InterfazGrafica)
        QtCore.QMetaObject.connectSlotsByName(InterfazGrafica)
        #Se le llama a función para tomar datos de interfaz
        self.btt_analizar.clicked.connect(self.manejoDatos)

    #Función que crea archivo, lee texto y regresa vocales y consonantes
    def manejoDatos(self):
        archivo = self.file_name.text() #Se toma nombre de cuadro de texto
        file = open(archivo + ".txt", "w+") #Se abre archivo que se creara
        escibir = self.txt.toPlainText() #Se lee el texto a escribir
        num = int(self.N_lineas.toPlainText()) #Se lee el número de lineas
        #Se cuentan las vocales
        vocales = sum(c in {"a", "A", "e", "E", "i", "I", "o", "O", "u", "U"} for c in escibir)
        conso = len(escibir) - vocales # Se determinan las consonantes
        # Se imprime en la MainWindow el numero de vocales y consonantes
        self.NV_output.setText(str(vocales * num))
        self.NC_output.setText(str(conso * num))

        # Guarda en el documento el texto n veces
        for x in range(0, num):
            file.writelines(escibir)
            file.write("\n")
            file.write("\n")

    #Funcion para retransladar el UI
    def retranslateUi(self, InterfazGrafica):
        _translate = QtCore.QCoreApplication.translate
        InterfazGrafica.setWindowTitle(_translate("InterfazGrafica", "MainWindow"))
        self.title_window.setHtml(_translate("InterfazGrafica", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">¡Bienvenido, compañero!</span></p></body></html>"))
        self.subt_1.setHtml(_translate("InterfazGrafica", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\"> ============== Sección de edición y escritura =============</span></p></body></html>"))
        self.subt_2.setHtml(_translate("InterfazGrafica", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\"> ================== Sección de análisis =================</span></p></body></html>"))
        self.btt_analizar.setText(_translate("InterfazGrafica", "Clic para analizar"))
        self.title_NV.setHtml(_translate("InterfazGrafica", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">Número de vocales</span></p></body></html>"))
        self.title_NC.setHtml(_translate("InterfazGrafica", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">Número de consonantes</span></p></body></html>"))
        self.title_FN.setHtml(_translate("InterfazGrafica", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">Nombre del archivo:</span></p></body></html>"))
        self.title_txtwrite.setHtml(_translate("InterfazGrafica", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">Texto a escribir:</span></p></body></html>"))
        self.title_LF.setHtml(_translate("InterfazGrafica", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">Número de líneas en archivo:</span></p></body></html>"))
        self.toolBar.setWindowTitle(_translate("InterfazGrafica", "toolBar"))
        self.actionEsc.setText(_translate("InterfazGrafica", "Esc"))

#Función main donde se le llaman a las funciones
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InterfazGrafica = QtWidgets.QMainWindow()
    ui = Ui_InterfazGrafica()
    ui.setupUi(InterfazGrafica)
    InterfazGrafica.show()
    sys.exit(app.exec_())
