# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Modulo4_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InterfazGrafica(object):
    def setupUi(self, InterfazGrafica):
        InterfazGrafica.setObjectName("InterfazGrafica")
        InterfazGrafica.resize(809, 705)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        InterfazGrafica.setFont(font)
        InterfazGrafica.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(InterfazGrafica)
        self.centralwidget.setObjectName("centralwidget")
        self.title_window = QtWidgets.QTextEdit(self.centralwidget)
        self.title_window.setEnabled(True)
        self.title_window.setGeometry(QtCore.QRect(190, 20, 411, 51))
        self.title_window.setAutoFillBackground(True)
        self.title_window.setReadOnly(True)
        self.title_window.setObjectName("title_window")
        self.subt_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.subt_1.setEnabled(True)
        self.subt_1.setGeometry(QtCore.QRect(-20, 90, 831, 31))
        self.subt_1.setAutoFillBackground(True)
        self.subt_1.setReadOnly(True)
        self.subt_1.setObjectName("subt_1")
        self.subt_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.subt_2.setEnabled(True)
        self.subt_2.setGeometry(QtCore.QRect(-20, 450, 831, 31))
        self.subt_2.setAutoFillBackground(True)
        self.subt_2.setReadOnly(True)
        self.subt_2.setObjectName("subt_2")
        self.btt_analizar = QtWidgets.QPushButton(self.centralwidget)
        self.btt_analizar.setGeometry(QtCore.QRect(340, 600, 121, 28))
        self.btt_analizar.setObjectName("btt_analizar")
        self.title_NV = QtWidgets.QTextEdit(self.centralwidget)
        self.title_NV.setEnabled(True)
        self.title_NV.setGeometry(QtCore.QRect(140, 500, 171, 31))
        self.title_NV.setAutoFillBackground(True)
        self.title_NV.setReadOnly(True)
        self.title_NV.setObjectName("title_NV")
        self.title_NC = QtWidgets.QTextEdit(self.centralwidget)
        self.title_NC.setEnabled(True)
        self.title_NC.setGeometry(QtCore.QRect(480, 500, 171, 31))
        self.title_NC.setAutoFillBackground(True)
        self.title_NC.setReadOnly(True)
        self.title_NC.setObjectName("title_NC")
        self.title_FN = QtWidgets.QTextEdit(self.centralwidget)
        self.title_FN.setEnabled(True)
        self.title_FN.setGeometry(QtCore.QRect(320, 130, 171, 31))
        self.title_FN.setAutoFillBackground(True)
        self.title_FN.setReadOnly(True)
        self.title_FN.setObjectName("title_FN")
        self.title_txtwrite = QtWidgets.QTextEdit(self.centralwidget)
        self.title_txtwrite.setEnabled(True)
        self.title_txtwrite.setGeometry(QtCore.QRect(320, 210, 171, 31))
        self.title_txtwrite.setAutoFillBackground(True)
        self.title_txtwrite.setReadOnly(True)
        self.title_txtwrite.setObjectName("title_txtwrite")
        self.title_LF = QtWidgets.QTextEdit(self.centralwidget)
        self.title_LF.setEnabled(True)
        self.title_LF.setGeometry(QtCore.QRect(190, 380, 231, 31))
        self.title_LF.setAutoFillBackground(True)
        self.title_LF.setReadOnly(True)
        self.title_LF.setObjectName("title_LF")
        self.N_lineas = QtWidgets.QLineEdit(self.centralwidget)
        self.N_lineas.setGeometry(QtCore.QRect(430, 380, 211, 31))
        self.N_lineas.setObjectName("N_lineas")
        self.file_name = QtWidgets.QLineEdit(self.centralwidget)
        self.file_name.setGeometry(QtCore.QRect(270, 170, 281, 31))
        self.file_name.setObjectName("file_name")
        self.txt = QtWidgets.QTextEdit(self.centralwidget)
        self.txt.setGeometry(QtCore.QRect(100, 250, 601, 111))
        self.txt.setObjectName("txt")
        self.NC_output = QtWidgets.QLineEdit(self.centralwidget)
        self.NC_output.setGeometry(QtCore.QRect(460, 540, 211, 41))
        self.NC_output.setObjectName("NC_output")
        self.NV_output = QtWidgets.QLineEdit(self.centralwidget)
        self.NV_output.setGeometry(QtCore.QRect(120, 540, 211, 41))
        self.NV_output.setObjectName("NV_output")
        InterfazGrafica.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(InterfazGrafica)
        self.statusbar.setObjectName("statusbar")
        InterfazGrafica.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(InterfazGrafica)
        self.toolBar.setObjectName("toolBar")
        InterfazGrafica.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionEsc = QtWidgets.QAction(InterfazGrafica)
        self.actionEsc.setObjectName("actionEsc")

        self.retranslateUi(InterfazGrafica)
        QtCore.QMetaObject.connectSlotsByName(InterfazGrafica)

    def retranslateUi(self, InterfazGrafica):
        _translate = QtCore.QCoreApplication.translate
        InterfazGrafica.setWindowTitle(_translate("InterfazGrafica", "MainWindow"))
        self.title_window.setHtml(_translate("InterfazGrafica", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">¡Bienvenido, compañero!</span></p></body></html>"))
        self.subt_1.setHtml(_translate("InterfazGrafica", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\"> ============== Sección de edición y escritura =============</span></p></body></html>"))
        self.subt_2.setHtml(_translate("InterfazGrafica", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\"> ================== Sección de análisis =================</span></p></body></html>"))
        self.btt_analizar.setText(_translate("InterfazGrafica", "Clic para analizar"))
        self.title_NV.setHtml(_translate("InterfazGrafica", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">Número de vocales</span></p></body></html>"))
        self.title_NC.setHtml(_translate("InterfazGrafica", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">Número de consonantes</span></p></body></html>"))
        self.title_FN.setHtml(_translate("InterfazGrafica", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">Nombre del archivo:</span></p></body></html>"))
        self.title_txtwrite.setHtml(_translate("InterfazGrafica", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">Texto a escribir:</span></p></body></html>"))
        self.title_LF.setHtml(_translate("InterfazGrafica", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">Número de líneas en archivo:</span></p></body></html>"))
        self.toolBar.setWindowTitle(_translate("InterfazGrafica", "toolBar"))
        self.actionEsc.setText(_translate("InterfazGrafica", "Esc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InterfazGrafica = QtWidgets.QMainWindow()
    ui = Ui_InterfazGrafica()
    ui.setupUi(InterfazGrafica)
    InterfazGrafica.show()
    sys.exit(app.exec_())
